[package]
name = "bfieldcodec_derive"
version = "0.7.0"
edition = "2021"
license = "GPL-2.0"
description = "Derive macro for BFieldCodec."

[dependencies]
syn = { version = "^2", features = ["full", "derive"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
